name: Setup PostgreSQL on macOS without Admin

on: [push]

jobs:
  postgresql-setup:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PostgreSQL Portable Edition
        run: |
          wget https://get.enterprisedb.com/postgresql/postgresql-14.1-1-osx-binaries.zip -O postgresql.zip
          unzip postgresql.zip -d $GITHUB_WORKSPACE
          mv $GITHUB_WORKSPACE/pgsql $GITHUB_WORKSPACE/postgresql

      - name: Setup PostgreSQL environment variables
        run: |
          echo 'export POSTGRESQL_HOME=$GITHUB_WORKSPACE/postgresql' >> $GITHUB_ENV
          echo 'export PATH=$POSTGRESQL_HOME/bin:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Initialize PostgreSQL data directory
        run: |
          initdb -D $GITHUB_WORKSPACE/postgresql_data

      - name: Start PostgreSQL server
        run: pg_ctl -D $GITHUB_WORKSPACE/postgresql_data -l logfile start

      - name: Wait for PostgreSQL to start
        run: |
          for i in {30..0}; do
            if pg_isready &>/dev/null; then
              break
            fi
            echo 'Waiting for PostgreSQL to start...'
            sleep 1
          done

      - name: Set up PostgreSQL user and database
        run: |
          psql -c "CREATE USER github WITH PASSWORD 'password';"
          psql -c "ALTER USER github WITH SUPERUSER;"
          psql -c "CREATE DATABASE test_db OWNER github;"

      - name: Verify PostgreSQL setup
        run: psql -c "\l"