name: Setup MariaDB

on: [push]

jobs:
  mariadb-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download MariaDB Portable Edition
        run: |
          wget https://downloads.mariadb.com/MariaDB/mariadb-10.6.5/winx64-packages/mariadb-10.6.5-winx64.zip -O mariadb.zip
          unzip mariadb.zip -d mariadb

      - name: Setup MariaDB environment variables
        run: |
          echo 'export MARIADB_HOME=$GITHUB_WORKSPACE/mariadb/mariadb-10.6.5-linux-x86_64/' >> $GITHUB_ENV
          echo 'export PATH=$MARIADB_HOME/bin:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Initialize MariaDB data directory
        run: mysqld --initialize-insecure --datadir=$GITHUB_WORKSPACE/mariadb_data

      - name: Start MariaDB server
        run: mysqld --datadir=$GITHUB_WORKSPACE/mariadb_data --skip-networking &

      - name: Wait for MariaDB to start
        run: |
          for i in {30..0}; do
            if mysqladmin ping &>/dev/null; then
              break
            fi
            echo 'Waiting for MariaDB to start...'
            sleep 1
          done

      - name: Set up MariaDB root user and basic database
        run: |
          mysql -e "CREATE USER 'github'@'localhost' IDENTIFIED BY 'password';"
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'github'@'localhost' WITH GRANT OPTION;"
          mysql -e "FLUSH PRIVILEGES;"
          mysql -e "CREATE DATABASE test_db;"

      - name: Verify MariaDB setup
        run: mysql -e "SHOW DATABASES;"